version: 2
jobs:
  build:
    branches:
      only:
        - master
        - webpacker

    machine: true

    steps:

      - checkout

      - run:
          name: Release
          command: sh script/release.sh
